use_frameworks!

target 'LocalNotificationFramework_Example' do
  pod 'LocalNotificationFramework', :path => '../'

  target 'LocalNotificationFramework_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
